### PR TITLE
update kubectl apply doc for required resource name

### PR DESCRIPTION
**Pull request by supereagle**
Update kubectl.yaml for kubernetes/kubernetes#44607

@pwittrock  PTAL.

### CODE REVIEW

**Comment by pwittrock** [comment]
@supereagle Actually, I don't understand why the new doc says the name must be provided.  What does that mean?

**Comment by supereagle** [comment]
@pwittrock `kubectl apply` will check the resource name and fail if it is missing. Some users may wan to use generateName instead of resource name in `kubectl apply`, so remind users to avoid this wrong usage by improving the doc. The detailed discussion can be referred in kubernetes/kubernetes#44501 and kubernetes/kubernetes#44527.

**Comment by supereagle** [comment]
@pwittrock  Are you clear about the purpose of this PR now?

**Comment by pwittrock** [comment]
Yup.  Thanks.

**Comment by supereagle** [comment]
OK. FYI, I think the PR #18 to revert this change can be closed.

**Pull request merged**
